# -*- coding: utf-8 -*-
"""Document_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E7w03C1CDhQQ11mZAHbPKZtEf7RSJ2-8
"""

import streamlit as st
from PIL import Image
import sys
import re
import json
from google import genai
from google.genai import types
import base64
import os

#if "google.colab" in sys.modules:
    # Authenticate user to Google Cloud
#    from google.colab import auth

#    auth.authenticate_user()
#os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/home/sjangbahadur/codes/llm-project-52521-798974421649.json"

def format_markdown_json(json_string):
  response_text = re.sub(r"json", "", json_string)
  response_text = re.sub(r"```", "", response_text)
  json_response = json.loads(response_text)
  return json_response

client = genai.Client(
      vertexai=True,
      project="ccinsights3",
      location="us-central1"
  )

def generate_analysis(doc_analysed):
  document1 = types.Part.from_uri(
      file_uri=doc_analysed,
      mime_type="application/pdf",
  )
  text1 = types.Part.from_text(text="""SYSTEM: ```You are an expert Indian lawyer specializing in motor vehicle accident claims. Your task is to meticulously analyze provided supporting documents related to a third-party motor claim. You must apply your deep understanding of Indian motor laws and legal procedures to extract relevant details, assess liability, and provide a reasoned recommendation for the claim. Your analysis should be based solely on the provided documentation. You are to output the final analysis and recommendation in a JSON format.```
INSTRUCTION: ```Carefully review all the provided documents. Your analysis must include, but is not limited to, the following aspects.
1. **Case Overview:** Briefly summarize the accident details including date, time, location and vehicle types involved, and the parties involved.
2. **Claimant Information:** Extract details regarding the claimant, including name, age, address, and nature of injuries sustained, if any. Also include the vehicle registration and its details.
3. **Insured Party Information:** Extract details about the insured party, including name, vehicle registration details, if any.
4. **Witness Testimony:** Identify and summarize witness statements, highlighting their observations of the accident and their assessment of fault, if any. Note the witness names and their contact information if available.
5. **Police Report Analysis:** Analyze any police reports submitted. Identify the key findings of the police investigation, including the assessment of fault, if any. Identify the FIR Number and the location of the police station.
6. **Accident Scene Details:** Describe the accident location including the type of road, condition of road and visibility conditions.
7. **Damage Assessment:** Summarize any damage assessments of the vehicles involved. Include the cost of repairs if available.
8. **Applicable Motor Laws:** Identify relevant sections of Indian motor laws pertinent to the case, e.g., The Motor Vehicles Act, 1988, relevant rules and guidelines for insurance claims, negligence, and liability.
9. **Liability Analysis:** Based on the extracted information, analyze who is at fault for the accident using Indian Motor Law. Explain with reasons. Include all possible scenarios of liabilities of different parties involved.
10. **Claim Recommendation:** Based on your complete analysis, make a clear recommendation on whether to approve the claim or contest it in an Indian court based on the principles of Indian Motor law. Explain the reasoning for your recommendation.
11. **Supporting Evidence:** List all documents that were provided for your review. This should be a list of strings which includes names of all documents used to prepare the analysis.
Your final output must be a single JSON object. The key of the object will be \"analysis\" and the value would be another JSON object containing the 11 points above as per below given output format.```
OUTPUT:
```json
{
 "analysis": {
  "case_overview": "",
  "claimant_information": {
   "name": "",
   "age": "",
   "address": "",
   "family_member": "",
   "vehicle_details": null,
   "injuries": ""
  },
  "insured_party_information": {
   "name": "",
   "vehicle_registration": "",
   "vehicle_type": ""
  },
  "witness_testimony": [
   {
    "name": "",
    "age": "",
    "address": "",
    "statement": ""
   }
  ],
  "police_report_analysis": {
   "fir_number": "",
   "police_station": "",
   "sections_applied": [
   ],
   "key_findings": ""
  },
  "accident_scene_details": {
   "location": "",
   "condition": "",
   "visibility": ""
  },
   "damage_assessment": {
   "vehicle_damage": "",
   "repair_costs": "If any else 'Not Applicable'",
   "losses" : "If any else 'Not Applicable'",
  },
  "applicable_motor_laws": [
  ],
  "liability_analysis": "",
  "actual_judgement" : "",
  "requested_compensation": "If any else 'Not Applicable'",
  "approved_compensation": "If any else 'Not Applicable'",
  "claim_recommendation": "Any recommended based on analyzed document as an Indian lawyer to an Insurance company",
  "defending_against_judgement": "Any recommended options as an Indian lawyer according to Indian Motor Law to avoid penalties in such case or counter the judgement as an Insurance company.",
  "provided_supporting_evidence": [
  ]
 }
}
```""")

  model = "gemini-2.0-flash-exp"
  contents = [
    types.Content(
      role="user",
      parts=[
        document1,
        text1
      ]
    )
  ]
  tools = [
    types.Tool(google_search=types.GoogleSearch())
  ]
  generate_content_config = types.GenerateContentConfig(
    temperature = 1,
    top_p = 0.95,
    max_output_tokens = 8192,
    response_modalities = ["TEXT"],
    safety_settings = [types.SafetySetting(
      category="HARM_CATEGORY_HATE_SPEECH",
      threshold="OFF"
    ),types.SafetySetting(
      category="HARM_CATEGORY_DANGEROUS_CONTENT",
      threshold="OFF"
    ),types.SafetySetting(
      category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
      threshold="OFF"
    ),types.SafetySetting(
      category="HARM_CATEGORY_HARASSMENT",
      threshold="OFF"
    )],
  )

  response = client.models.generate_content(
    model = model,
    contents = contents,
    config = generate_content_config,
    )
  print(response.text)
  return response.text

#content_compliance_json = format_markdown_json(generate_analysis("gs://sjangbahadur-test/customer_sample_doc/GUJARATI - FIR.pdf"))

def display_json(json_data):
    """Displays JSON data in a structured format using Streamlit."""

    st.write("## Analysis Report")
    try:
        # Check if the input is a valid JSON string and parse it
        if isinstance(json_data, str):
            json_data = json.loads(json_data)

        if isinstance(json_data, dict) and "analysis" in json_data:
            analysis = json_data["analysis"]
            for key, value in analysis.items():
                st.subheader(f"***{key.replace('_', ' ').title()}***", divider="gray")
                if isinstance(value, dict):
                    for sub_key, sub_value in value.items():
                        st.write(f"- **{sub_key.replace('_', ' ').title()}**: {sub_value}")
                elif isinstance(value, list):
                    for item in value:
                        if isinstance(item, dict):
                            for sub_key, sub_value in item.items():
                                st.write(f" - **{sub_key.replace('_',' ').title()}**: {sub_value}")
                        else:
                           st.write(f"- {item}")

                else:
                    st.write(f"- {value}")
        else:
            st.write("Invalid JSON format. 'analysis' key not found.")

    except json.JSONDecodeError:
        st.write("Invalid JSON input.")


# Example usage (replace with your actual JSON data)
#display_json(content_compliance_json)

def main():
    st.title("3rd Party Motor Claims Analysis")

    # Load the logo image
    logo_image = Image.open("hdfc-ergo-logo.png")

    # Display the logo in the sidebar
    st.sidebar.image(logo_image, use_container_width=True)

    # Document selection dropdown
    document_options = {
        "Claim-1001": "gs://hdfc-ergo-motor-claim-analysis/GUJARATI - JUDGEMENT - SCAN COPY.pdf",
        "Claim-1002": "gs://hdfc-ergo-motor-claim-analysis/TAMIL FIR.pdf",
        "Claim-1003": "gs://hdfc-ergo-motor-claim-analysis/TAMIL STATEMENT.pdf",
        "Claim-1004": "gs://hdfc-ergo-motor-claim-analysis/TAMIL STATEMENT.pdf",
        "Claim-1005": "gs://hdfc-ergo-motor-claim-analysis/TAMIL STATEMENT.pdf",
    }

    selected_document = st.selectbox("Select Claim Number", list(document_options.keys()))

    if st.button("Analyze"):
        try:
          doc_uri = document_options[selected_document]
          analysis_result = generate_analysis(doc_uri)
          content_compliance_json = format_markdown_json(analysis_result)  # Properly format JSON

          # Display the formatted JSON analysis
          st.subheader("Analysis Results:")
          st.json(content_compliance_json)
          display_json(content_compliance_json)

        except Exception as e:
            st.error(f"An error occurred: {e}")

if __name__ == "__main__":
    main()
